'use strict';

/**
 * build.js — Deterministic single-file bundler producing dist/zerotask.js.
 *
 * Pipeline:
 *   1. Lexically analyzes require() calls in src/ modules.
 *   2. Resolves and topologically sorts module dependencies.
 *   3. Wraps each module in a CommonJS runtime registry shim.
 *   4. Emits deterministic bundle without timestamps or machine paths.
 */

const fs     = require('fs');
const path   = require('path');
const crypto = require('crypto');

const SRC_DIR  = path.join(__dirname, 'src');
const OUT_DIR  = path.join(__dirname, 'dist');
const OUT_FILE = path.join(OUT_DIR, 'zerotask.js');

const ENTRY_MODULES = [
  'logger',
  'config',
  'taskgraph',
  'processmanager',
  'retry',
  'shutdown',
  'envloader',
  'scheduler',
  'cli',
];

/**
 * Extracts require() argument strings from source code.
 *
 * @param {string} source
 * @returns {string[]}
 */
function extractRequires(source) {
  const pattern = /require\s*\(\s*(['"`])([^'"`\n]+)\1\s*\)/g;
  const deps    = [];
  let match;
  while ((match = pattern.exec(source)) !== null) {
    deps.push(match[2]);
  }
  return deps;
}

/**
 * Filters and resolves local src/ dependencies.
 *
 * @param {string[]} requires
 * @returns {string[]}
 */
function resolveSrcDeps(requires) {
  return requires
    .filter(r => r.startsWith('./') || r.startsWith('../'))
    .map(r => path.basename(r, '.js'))
    .filter(name => ENTRY_MODULES.includes(name));
}

/**
 * Builds dependency graph across all ENTRY_MODULES.
 *
 * @returns {Map<string, string[]>}
 */
function buildModuleGraph() {
  const graph = new Map();

  for (const name of ENTRY_MODULES) {
    const filePath = path.join(SRC_DIR, `${name}.js`);
    if (!fs.existsSync(filePath)) {
      graph.set(name, []);
      continue;
    }
    const source   = fs.readFileSync(filePath, 'utf8');
    const requires = extractRequires(source);
    const deps     = resolveSrcDeps(requires);
    graph.set(name, deps);
  }

  return graph;
}

/**
 * Topologically sorts modules using Kahn's algorithm.
 *
 * @param {Map<string, string[]>} graph
 * @returns {string[]}
 */
function topoSort(graph) {
  const inDeg = new Map();
  for (const node of graph.keys()) inDeg.set(node, 0);
  for (const [, deps] of graph) {
    for (const dep of deps) {
      inDeg.set(dep, (inDeg.get(dep) || 0));
    }
  }
  for (const [node, deps] of graph) {
    inDeg.set(node, deps.length);
  }

  const queue = [];
  for (const [node, deg] of inDeg) {
    if (deg === 0) queue.push(node);
  }

  const result = [];
  while (queue.length > 0) {
    const node = queue.shift();
    result.push(node);
    for (const [dependent, deps] of graph) {
      if (deps.includes(node)) {
        const newDeg = inDeg.get(dependent) - 1;
        inDeg.set(dependent, newDeg);
        if (newDeg === 0) queue.push(dependent);
      }
    }
  }

  return result;
}

/**
 * Wraps a module in a CommonJS shim for bundle registry lookup.
 *
 * @param {string} name
 * @param {string} source
 * @returns {string}
 */
function wrapModule(name, source) {
  const stripped = source.replace(/^#!.*\n/, '');

  return [
    `_registry['${name}'] = (function() {`,
    `  const module  = { exports: {} };`,
    `  const exports = module.exports;`,
    `  const require = _require.bind(null, '${name}');`,
    `  (function() {`,
    stripped.split('\n').map(l => `    ${l}`).join('\n'),
    `  })();`,
    `  return module.exports;`,
    `})();`,
    '',
  ].join('\n');
}

/**
 * Concatenates shim and wrapped modules into a single bundle.
 *
 * @param {string[]} orderedModules
 * @returns {string}
 */
function emitBundle(orderedModules) {
  const lines = [];

  lines.push('#!/usr/bin/env node');
  lines.push("'use strict';");
  lines.push('');
  lines.push('/**');
  lines.push(' * ZeroTask — zero-dependency task runner for Node.js');
  lines.push(' * Bundled by build.js — do not edit this file directly.');
  lines.push(' */');
  lines.push('');
  lines.push('const _registry = Object.create(null);');
  lines.push('const _nodeRequire = require;');
  lines.push('');
  lines.push('function _require(fromModule, id) {');
  lines.push('  if (id.startsWith(\'./\') || id.startsWith(\'../\')) {');
  lines.push('    const name = id.replace(/^\\.\\.\\/src\\//, \'\').replace(/^\\.\\//, \'\').replace(/\\.js$/, \'\');');
  lines.push('    if (_registry[name]) return _registry[name];');
  lines.push('  }');
  lines.push('  return _nodeRequire(id);');
  lines.push('}');
  lines.push('');

  for (const name of orderedModules) {
    const filePath = path.join(SRC_DIR, `${name}.js`);
    if (!fs.existsSync(filePath)) {
      continue;
    }
    const source = fs.readFileSync(filePath, 'utf8');
    lines.push(wrapModule(name, source));
  }

  lines.push("_registry['cli'];");
  lines.push('');

  return lines.join('\n');
}

/**
 * Builds the distribution artifact.
 */
function build() {
  console.log('ZeroTask build starting...');

  if (!fs.existsSync(OUT_DIR)) {
    fs.mkdirSync(OUT_DIR, { recursive: true });
  }

  const graph   = buildModuleGraph();
  const ordered = topoSort(graph);

  console.log(`Module order: ${ordered.join(' → ')}`);

  const bundle = emitBundle(ordered);

  const tmpFile = `${OUT_FILE}.tmp`;
  fs.writeFileSync(tmpFile, bundle, 'utf8');
  fs.renameSync(tmpFile, OUT_FILE);

  try {
    fs.chmodSync(OUT_FILE, 0o755);
  } catch (_) {
    // chmod not supported on Windows
  }

  const bytes = fs.statSync(OUT_FILE).size;
  const hash = crypto.createHash('sha256').update(fs.readFileSync(OUT_FILE)).digest('hex');

  console.log(`\nOutput: dist/zerotask.js (${bytes} bytes)`);
  console.log(`SHA-256: ${hash}`);
  console.log('Build complete.');
}

if (require.main === module) {
  build();
} else {
  build();
}

module.exports = { build };
